CROWD_DETECTOR_DATA:
  MAIN_DATA:
    MIN_DISTANCE: 0.25
    YOLO_CONFIDENCE: 0.2
    BBOX_CONFIDENCE: 0.1
    KEY_POINTS_CONFIDENCE: 0.1
    MIN_CROWD_NUM_OF_PEOPLE: 2
    MAX_CROWD_NUM_OF_PEOPLE: null
    SCENE_SIZE: 'medium'  # large, medium, small
  PLOT_DATA:
    MAIN_COLOR:
    - 0
    - 255
    - 0
    ADDITIONAL_COLOR:
    - 0
    - 0
    - 255
    ADDITIONAL_COLOR_VISIBILITY: 0.4
