MAIN_CONFIGURATIONS_DATA:
  YOLO_CONFIDENCE: 0.5
  BBOX_CONFIDENCE: 0.5
  KEY_POINTS_CONFIDENCE: 0.5

CROWD_DETECTOR_DATA:
  MIN_DISTANCE: 0.25
  MIN_CROWD_NUM_OF_PEOPLE: 2
  MAX_CROWD_NUM_OF_PEOPLE: null
  SCENE_SIZE: 'medium'  # large, medium, small
  IOU_THRESHOLD: 0.5
  IOU_CROWD_THRESHOLD: 0.3

ACTIVE_GESTURES_DETECTOR_DATA:
  DELTA_ANGLE_THRESHOLD: 30
  MAX_ACTIVE_GESTURES: 10

PLOT_DATA:
  MAIN_COLOR:
  - 0
  - 255
  - 0
  ADDITIONAL_COLOR:
  - 0
  - 0
  - 255
  ADDITIONAL_COLOR_VISIBILITY: 0.4
