CROWD_DETECTOR_DATA:
  MAIN_DATA:
    MIN_DISTANCE: 0.45
    YOLO_CONFIDENCE: 0.3
    BBOX_CONFIDENCE: 0.5
    KEY_POINTS_CONFIDENCE: 0.7
    MIN_CROWD_NUM_OF_PEOPLE: 2
    MAX_CROWD_NUM_OF_PEOPLE: null
    KMEANS_N_CLUSTERS: 1
  PLOT_DATA:
    MAIN_COLOR:
    - 0
    - 255
    - 0
    ADDITIONAL_COLOR:
    - 0
    - 0
    - 255
    ADDITIONAL_COLOR_VISIBILITY: 0.4
